product_list:
  path: /api/product/
  controller: App\Controller\ProductController::listProducts
  methods: [GET,OPTIONS]

user_list:
  path: /api/user/
  controller: App\Controller\UserController::listUsers
  methods: [GET,OPTIONS]

order_list:
  path: /api/order/
  controller: App\Controller\OrderController::listOrdersByName
  methods: [GET,OPTIONS]

order_by_id:
  path: /api/order/{id}
  controller: App\Controller\OrderController::orderById
  methods: [GET,OPTIONS]


order_create:
  path: /api/order/
  controller: App\Controller\OrderController::createOrder
  methods: [POST,OPTIONS]

